global:
  scrape_interval: 5s  # scrape every 5 seconds

scrape_configs:
  - job_name: "fastapi_app"
    static_configs:
      # Replace 8000 with whichever port your FastAPI app runs on
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"  # if your metrics are exposed at /metrics
