# .bashrc

PS1='%n@%m:%~$ '

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
EDITOR=vim
export EDITOR

bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward

# enable vim keyboard binding
set -o vi
HISTSIZE=130000 HISTFILESIZE=-1
HISTSIZE=130000 HISTFILESIZE=-1

shopt -s histappend
history -a
history -n
export PROMPT_COMMAND="history -a; history -n"

bind "\e[A":history-search-backward
bind "\e[B":history-search-forward
